_core:
  default_config_hash: VqK3B1yO8uDA-vNNPfYtzDFnKyngazUHWFm9B-qzB4s
selected_provider: openshift_orchestration_provider
connection:
  endpoint: 'https://172.17.0.1:8443'
  token: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJteXByb2plY3QiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoic2hlcGhlcmQtdG9rZW4tNmhwcXoiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoic2hlcGhlcmQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI4OTQxMGNjYy1iYWNiLTExZWMtYmMyNy1lMGQ1NWUyODMyZjIiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6bXlwcm9qZWN0OnNoZXBoZXJkIn0.EgyDlPLK8R-azjUhPaU9GD9hOMGhLlBhMD5lB3wLsDwswFvTV9WMO-nESt2VAxMaLkUww0jn2spmhQQuf1MkXstn1RJIqxbkElLiU7vGiB4MidrIZRLH8y2Velt7UJxSkrMA77grBClYetqnGvdtGubKGgSqZKy2SqeLBMZh8gtvejlOAOiN2rZP5iJ2HDmAhl3R3BkI9C9HcEfI8y4sMony2A_U3HeGcJZ3iv2pIeSIlwwVK66X7f_ovZcG4mDIIVjlYGOeqSnsUqVM5_-FD_nLzx-3xdfLSpm1nFFIq8t0lPglgQQQtKehO3bOQmgxJjZHM1TODJ_fcmoYU4MYHA
  namespace: myproject
  verify_tls: false
queued_operations: true
