application: uofa/lamp

deps: &deps
  - composer install --prefer-dist --no-progress
  - npm install
  - bundle install --path vendor/bundle

test: &test
  - bin/phing ci:phpcs
  - bin/phing
  - bin/phing styleguide:link
  # Fix permissions issues for the Apache web user.
  - chown -R www-data:www-data app

test_pr:
  setup: *deps
  steps: *test

test_head:
  setup: *deps
  steps: *test

deploy_setup: &deploy_setup
  - bin/phing generate

deploy_qa:
  setup: *deps
  steps:
    - bin/phing generate
    - bundle exec cap dev deploy

deploy_staging:
  setup: *deps
  steps:
    - bin/phing generate
    - bundle exec cap staging deploy
