application: uofa/ua-lamp

deps: &deps

test: &test
  - robo build
  # Fix permissions issues for the Apache web user.
  - chown -R www-data:www-data app

test_pr:
  setup: *deps
  steps: *test

test_head:
  setup: *deps
  steps: *test

deploy_qa:
  setup: *deps
  steps:
    - bundle exec cap dev deploy

deploy_staging:
  setup: *deps
  steps:
    - bundle exec cap staging deploy

deploy_uasm:
  setup: *deps
  steps:
    - bundle exec cap uasm deploy
