application: uofa/lamp

test: &test
  - composer install --prefer-dist --no-progress
  - npm install
  - bin/phing ci:phpcs
  - bin/phing
  # Fix permissions issues for the Apache web user.
  - chown -R www-data:www-data app

test_pr:
  steps: *test

test_head:
  steps: *test

deploy_setup: &deploy_setup
  - bundle install --path vendor/bundle
  - npm install

deploy_qa:
  setup: *deploy_setup
  steps:
    - bundle exec cap dev deploy

deploy_staging:
  setup: *deploy_setup
  steps:
    - bundle exec cap staging deploy
