application: uofa/lamp

test: &test
  - composer install --prefer-dist --dev --no-progress
  - bin/phing
  # This is to fix issues we might have between the running user
  # and the web user.
  - chown -R www-data:www-data app

test_pr:
  steps: *test

test_head:
  steps: *test

deploy_setup: &deploy_setup
  - bundle install --path vendor/bundle

deploy_qa:
  setup: *deploy_setup
  steps:
    - bundle exec cap dev deploy

deploy_staging:
  setup: *deploy_setup
  steps:
    - bundle exec cap staging deploy
