ua_site_config_export.download:
  path: '/site-config/export/{nid}'
  defaults:
    _controller: '\Drupal\ua_site_config_export\Controller\SiteConfigExportController::download'
  requirements:
    _permission: 'administer'
