# Configuration schema for ua_sm_custom module

ua_sm_custom.settings:
  type: mapping
  label: 'Site Manager settings'
  mapping:
    jenkins:
      type: mapping
      label: 'Jenkins Build Server'
      mapping:
        enabled:
          type: boolean
          label: 'Enabled'
        base_uri:
          type: string
          label: 'Base URI'
        token:
          type: string
          label: 'Token'
        provision_job:
          type: string
          label: 'Provision Job'
        deploy_job:
          type: string
          label: 'Deploy Job'
        decommission_job:
          type: string
          label: 'Decommission Job'
        destroy_job:
          type: string
          label: 'Destroy Job'
        backup_job:
          type: string
          label: 'Backup Job'
        restore_job:
          type: string
          label: 'Restore Job'
    ldap:
      type: mapping
      label: 'LDAP Integration'
      mapping:
       enabled:
        type: boolean
        label: 'Enabled'
    controlled_roles:
      type: mapping
      label: 'Controlled Roles'
      mapping:
        administrator:
          type: string
          label: 'Administrator'
        uasm_developer:
          type: string
          label: 'Developer'
        uasm_online_consultant:
          type: string
          label: 'Online Consultant'
        uasm_site_administrator:
          type: string
          label: 'Site Administrator'
        uasm_web_author:
          type: string
          label: 'Web Author'
        uasm_content_editor:
          type: string
          label: 'Content Editor'
    backup_service:
      type: mapping
      label: 'Backup Service'
      mapping:
        path:
          type: string
          label: 'Backup path'
    environment_domains:
      type: mapping
      label: 'Environments and Domains'
      mapping:
        prd:
          type: string
          label: 'adelaide.edu.au'
        stg:
          type: string
          label: 'stg.adelaide.edu.au'
        uat:
          type: string
          label: 'uat.adelaide.edu.au'
        dev:
          type: string
          label: 'test'
