# Configuration schema for ua_sm_custom module

ua_sm_custom.settings:
  type: mapping
  label: 'Site Manager settings'
  mapping:
    jenkins:
      type: mapping
      label: 'Jenkins Build Server'
      mapping:
       enabled:
        type: boolean
        label: 'Enabled'
       path:
        type: string
        label: 'Path'
       token:
        type: string
        label: 'Token'
       job:
        type: string
        label: 'Job'
    ldap:
      type: mapping
      label: 'LDAP Integration'
      mapping:
       enabled:
        type: boolean
        label: 'Enabled'
