# Configuration schema for ua_sm_custom module

ua_sm_custom.settings:
  type: mapping
  label: 'Site Manager settings'
  mapping:
    jenkins:
      type: mapping
      label: 'Jenkins Build Server'
      mapping:
        enabled:
          type: boolean
          label: 'Enabled'
        base_uri:
          type: string
          label: 'Base URI'
        token:
          type: string
          label: 'Token'
        provision_job:
          type: string
          label: 'Provision Job'
        deploy_job:
          type: string
          label: 'Deploy Job'
        decommission_job:
          type: string
          label: 'Decommission Job'
        destroy_job:
          type: string
          label: 'Destroy Job'

    ldap:
      type: mapping
      label: 'LDAP Integration'
      mapping:
       enabled:
        type: boolean
        label: 'Enabled'

    controlled_roles:
      type: mapping
      label: 'Controlled Roles'
      mapping:
        administrator:
          type: string
          label: 'Administrator'
        uasm_developer:
          type: string
          label: 'Developer'
        uasm_online_consultant:
          type: string
          label: 'Online Consultant'
        uasm_site_administrator:
          type: string
          label: 'Site Administrator'
        uasm_web_author:
          type: string
          label: 'Web Author'
        uasm_content_editor:
          type: string
          label: 'Content Editor'
        uasm_wizard:
          type: string
          label: 'YOURE A WIZARD HARRY'
